ZipsAR/UnityAR_FoxRain

Assets/TaeHyeon.meta
Assets/TaeHyeon/Cylinder.prefab
Assets/TaeHyeon/Cylinder.prefab.meta
Assets/TaeHyeon/Scripts.meta
Assets/TaeHyeon/Scripts/CubeSpawner.cs
Assets/TaeHyeon/Scripts/CubeSpawner.cs.meta
Assets/TaeHyeon/Scripts/DrawCamGizmos.cs
Assets/TaeHyeon/Scripts/DrawCamGizmos.cs.meta
Assets/TaeHyeon/Scripts/LoggerTester.cs
Assets/TaeHyeon/Scripts/LoggerTester.cs.meta
Assets/TaeHyeon/Scripts/Player.cs
Assets/TaeHyeon/Scripts/Player.cs.meta
Assets/TaeHyeon/Scripts/Utils.meta
Assets/TaeHyeon/Scripts/Utils/Logger.cs
Assets/TaeHyeon/Scripts/Utils/Logger.cs.meta
Assets/TaeHyeon/Scripts/Utils/Singleton.cs
Assets/TaeHyeon/Scripts/Utils/Singleton.cs.meta
Assets/TaeHyeon/Stroll Default AR plane.prefab
Assets/TaeHyeon/Stroll Default AR plane.prefab.meta
Assets/TaeHyeon/StrollMode.unity
Assets/TaeHyeon/StrollMode.unity.meta
Assets/TaeHyeon/ar_plane_mat.mat
Assets/TaeHyeon/ar_plane_mat.mat.meta
Assets/TaeHyeon/planeColor.mat
Assets/TaeHyeon/planeColor.mat.meta
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/ProjectSettings.asset

Assets/taehyeon 폴더 생성
산책모드 씬 파일 생성
AR plane detect 후 raycast 충돌지점에 object생성 기능 구현 확인
ZipsAR.Logger 사용하기 위해 project settings의 scriptingDefineSymbols에 “ENABLE_LOG” 추가
ARRaycastManager로 AR plane의 충돌 처리는 동작하지 않음
Physics.raycast를 사용하여 충돌처리 구현

AR plane 인식 및 ray충돌 지점 object 생성

---

Assets/TaeHyeon/InteractMode.unity
Assets/TaeHyeon/Intro.unity
Assets/TaeHyeon/Intro.unity.meta
Assets/TaeHyeon/Materials/Gray.mat
Assets/TaeHyeon/Materials/Gray.mat.meta
Assets/TaeHyeon/PhysicsButton.cs
Assets/TaeHyeon/PhysicsButton.cs.meta
Assets/TaeHyeon/Scripts/GameManager.cs
Assets/TaeHyeon/Scripts/HandAttacher.cs
Assets/TaeHyeon/Scripts/HandController.cs
Assets/TaeHyeon/Scripts/InteractManager.cs
Assets/TaeHyeon/Scripts/PetBase.cs
Assets/TaeHyeon/Scripts/Player.cs
Assets/TaeHyeon/Scripts/StrollManager.cs
Assets/TaeHyeon/Scripts/Utils/Singleton.cs

1. Intro Scene에서 InteractMode 이동할 수 있도록 구현
2. Intro에서는 AR Session과 AR Session Origin, GameManager를 Dontdestory로 설정
3. pushable 버튼은 인식된 손을 통해서 물리적으로 누를 수 있음, 추후 구매나 게임 시작등에 사용할수 있을 것으로 보임
이후 이동하는 다른 씬에서는 AR 관련 오브젝트를 비활설화 해야함
각 모드를 관리하는 Manager는 씬이 전환되는 순간 GameManager에 등록해야 함

인트로 씬 및 pushable button 구현

---

Assets/TaeHyeon/Animation/Cat/A_eat.anim
Assets/TaeHyeon/Animation/Cat/A_eat.anim.meta
Assets/TaeHyeon/Animation/Cat/A_idle.anim
Assets/TaeHyeon/Animation/Cat/C_Sleep.anim
Assets/TaeHyeon/Animation/Cat/C_Sleep.anim.meta
Assets/TaeHyeon/Animation/Dog/A_eat.anim.meta
Assets/TaeHyeon/Animation/Dog/C_sleep.anim.meta
Assets/TaeHyeon/Animation/DogController.overrideController
Assets/TaeHyeon/Animation/PetController.controller
Assets/TaeHyeon/HandUIAttacher.cs
Assets/TaeHyeon/HandUIAttacher.cs.meta
Assets/TaeHyeon/HandUIController.cs
Assets/TaeHyeon/HandUIController.cs.meta
Assets/TaeHyeon/Prefabs/Comb.prefab
Assets/TaeHyeon/Prefabs/Comb.prefab.meta
Assets/TaeHyeon/Prefabs/HandUI.prefab
Assets/TaeHyeon/Prefabs/HandUI.prefab.meta
Assets/TaeHyeon/Prefabs/Snack.prefab
Assets/TaeHyeon/Scenes/InteractMode.unity
Assets/TaeHyeon/Scenes/Intro.unity
Assets/TaeHyeon/Scripts/Cat.cs
Assets/TaeHyeon/Scripts/Comb.cs
Assets/TaeHyeon/Scripts/Comb.cs.meta
Assets/TaeHyeon/Scripts/Dog.cs
Assets/TaeHyeon/Scripts/InteractManager.cs
Assets/TaeHyeon/Scripts/PetBase.cs
Assets/TaeHyeon/Scripts/Snack.cs

기존 - IM에서 조건 만족시 직접 cmd 실행에서
변경 - IM에서 조건 만족시 queue에 cmd를 저장, 이후 queue에서 하나씩 순서대로 명령어를 실행
1. 먹이를 잡아서 던지면 펫이 먹이 방향으로 다가가서 먹음
2. 빗을 잡아서 몸쪽에 1초간 부딫히면 빗질 받음
천천히 진행하는 먹이, 빗 상호작용은 이상없이 동작
but, 애니메이션 종료을 기다리지 않고 바로 다른 동작을 하는 경우, 상호작용이 멈추는 이슈 존재
미 해결 이슈
1. 먹이를 던지고 펫이 먹기 전에 다시 잡아 던지는 경우 펫이 이전 먹이 위치로 이동하는 이슈
2. 빗질 애니메이션이 실행 중일때, 다시 빗질하면 이후 명령어가 실행되지 않는 이슈

먹이 및 빗질 상호작용 구현

---

Assets/Plugins/ARPG Effects/Upgrades/ARPGFX URP Upgrade (2019.3.10f1).unitypackage.meta
Assets/Plugins/Sparkles/Upgrades/Sparkle FX LWRP 2019.2.3f1 Materials.unitypackage.meta
Assets/Plugins/Sparkles/Upgrades/Sparkle FX Standard Materials.unitypackage.meta
Assets/Plugins/Sparkles/Upgrades/Sparkle FX URP 2019.3.1f1 Materials.unitypackage.meta

유구한 전통의 unitypackage 삭제 로그 내역 문제 해소
자꾸 unity package가 삭제되었다는 불안한 문구가 떠서 핫픽스 파서 해당 내역 커밋 시킨 뒤
병합하려는 것.
유니티 패키지는 git ignore대상이다~

assets plugin unitypackage추적 삭제

---

Assets/TaeHyeon/Scripts/InteractManager.cs

시간(1s)	움직임(1m)
배고픔	2 감소	5 감소
청결도	1 감소	2 감소
피로도	1 증가	2 증가

시간 거리에 따라 펫 스탯 변동 구현

---

Assets/DongHyuk/Scripts/ButtonManager.cs
Assets/Jaewon2/Scene/StoreScene.unity
Assets/Jaewon2/Script/UICon.cs
Assets/Plugins/Borodar/RainbowFolders/Editor/Data/RainbowFoldersRuleset.asset
Assets/TaeSeung/Scene/HousingMode.unity
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/ProjectSettings.asset

handUI에서 하우징 모드 이동할 때 사용하는 씬 이름 수정
GirdHousing -> HousingMode
상점의 한글(현재잔액)부분 삭제
각 이름 폴더에 색깔 적용

!BREAKING CHANGE: 각 파트 통합 후 오류 사항 수정

---

Assets/Samples/Snapdragon Spaces/0.14.0/Core Samples/Shared Assets/Prefabs/Interaction/Interaction.prefab

Interaction.prefab이 수정되어 입력모드를 변경할떄마다 오류 발생했었음
Interaction.prefab을 "7f89b26" 커밋으로 되돌리는 것으로 오류 수정

hotfix: GazePointer reference 오류 수정

---

Assets/TaeHyeon/Audios/intro_bgm.mp3.meta
Assets/TaeHyeon/Scenes/Intro.unity
Assets/TaeHyeon/Scripts/Managers/InteractManager.cs

상호작용 모드 오류 수정
OnDestroy -> OnDisable

Feat: 인트로 bgm 추가

---

Assets/TaeHyeon/Scripts/Managers/InteractManager.cs
Assets/TaeHyeon/Scripts/Pets/Cat.cs
Assets/TaeHyeon/Scripts/Pets/Dog.cs
Assets/TaeHyeon/Scripts/Pets/PetBase.cs

pet stat 로컬 파일에 Load Save 기능 구현
로컬파일이 없는 경우, 기존에 Dog.cs, Cat.cs의 값으로 초기화 됨

pet stat 로컬 파일에 save 및 load 구현

---

Assets/DongHyuk/Prefabs/LeftHandUI_Logo.prefab
Assets/DongHyuk/Scripts/ButtonManager.cs

1. InteractionMode에서 HandUI - 아이템 생성시 의자 0.1사이즈로 왼손에 생성
1. 하우징 모드에서 HandUI 버튼 위치 수정 (사용자 slip이 줄어들도록 버튼이 안 겹치게 위치수정)
2. 모드가 변경돼도 HandUI가 변경되지 않는 오류 수정

왼손기준으로 아이템 생성

---

Assets/TaeHyeon/Prefabs/Ball.prefab
Assets/TaeHyeon/Prefabs/Ball.prefab.meta
Assets/TaeHyeon/Scenes/InteractMode.unity
Assets/TaeHyeon/Scripts/Managers/InteractManager.cs
Assets/TaeSeung/Script/DatabaseScript/NormalDatabase/HousingObjectdatabase.cs

공의 날라가는 속도 증가, 공의 무게 증가
stat 불러오는 부분
stat 파일이 저장이 안되있는 경우, Dog, Cat 에 저장되어 있는 기본 값으로 초기화 후, 
초기화된 데이터를 상호작용 시작하기 전에 로컬파일에 저장
stat 파일이 저장이 되있는 경우, 저장된 로컬 파일에서 스탯을 불러와 상호작용에서 사용
stat을 저장하는 부분
상호작용 모드를 나갈 때

펫 스탯 Glass에서 저장 안되는 오류 수정 및 공 장난감 추가

---

Assets/TaeSeung/Asset/ProximalSnappingCube.prefab
Assets/TaeSeung/Asset/ProximalSnappingCube.prefab.meta
Assets/TaeSeung/Prefab/Button.prefab
Assets/TaeSeung/Prefab/Button.prefab.meta
Assets/TaeSeung/Scene/HousingMode.unity
Assets/TaeSeung/Script/CursorCollisionSystem.cs
Assets/TaeSeung/Script/MapInfo.cs
Assets/TaeSeung/Script/PlacementSystem.cs
Assets/TaeSeung/Script/UISystem/TestButton.cs
Assets/TaeSeung/Shader/Transparent.mat

MAPINFO : visiblemode로 바꿔주는 코드가 추가됨 
함수명 : SetVisiblemode()
PlacementSystem : 현재 하우징 가구 배치 불가 영역에 대한 알고리즘 개선 작업중입니다.
+ 하우징 가구 배치 가능 영역 표시에 대한 color적용 오류 개선

Grid Housing AR 중간 결산 3

---

Assets/Jaewon2/Prefabs/Default.prefab
Assets/Jaewon2/Prefabs/ItemButton.prefab
Assets/Jaewon2/Prefabs/ItemButton_Inven.prefab
Assets/Jaewon2/Script/ItemMov.cs
Assets/Jaewon2/Script/ParticleManager.cs

터치 시 작동하도록 변경
-기존에 버튼 인식 시 불러오던 함수들을 그대로 OntriggerEnter()때 호출하도록 만들었습니다. -기존의 핀치로의 작동도 살아 있으므로, 필요하면 그때 Button 컴포넌트(핀치 시 작동)도 지우겠습니다.

버튼 터치 시 작동하도록 변경(기기 테스트X)

---

Assets/TaeHyeon/Scripts/Managers/GameManager.cs

상호작용으로 넘어갈 때 하우징 안 보이게 핫픽스함
Game Manager 클래스 한줄 추가한 수준

상호작용 모드 넘어갈 때 하우징 안 보이게 핫픽스

---

Assets/Jaewon2/Prefabs/Default.prefab
Assets/Jaewon2/Prefabs/snack/Treat_01.prefab.meta
Assets/Jaewon2/Prefabs/toy/BoneToy_01.prefab.meta
Assets/Jaewon2/Prefabs/toy/Comb_01.prefab.meta
Assets/Jaewon2/Scene/StoreScene.unity
Assets/Jaewon2/Script/GetData.cs
Assets/Jaewon2/Script/ItemMov.cs
Assets/Jaewon2/Script/TestJson.cs
Assets/Jaewon2/Script/UICon.cs

PR merge문제 해결

---

Assets/Jaewon2/Prefabs/Default.prefab
Assets/Jaewon2/Scene/StoreScene.unity
Assets/Jaewon2/Script/TestJson.cs
Assets/Jaewon2/Script/UICon.cs

merge시 문제 해결(폰트 깨짐, 사운드 버그, json호출버그)

---

Assets/TaeHyeon/Scenes/InteractMode.unity
Assets/TaeHyeon/Scenes/Intro.unity
Assets/TaeHyeon/Scripts/Pets/PetBase.cs

1. 펫 등속운동으로 변경
2. 인트로씬에서 종료 및 테스트 ui 삭제
3. 상호작용 펫 선택 ui 가로 간격 늘림
4. 손 상호작용 사운드 추가

펫 등속운동으로 변경

---

Assets/Jaewon2/Prefabs/Default.prefab
Assets/Jaewon2/Scene/StoreScene.unity
Assets/Jaewon2/Script/GetData.cs

-상점 측에서 구현되는 아이템 정보(현재 개수, 판매, 구매 가격) 출력

추가 기능 구현 최종

---

Assets/DongHyuk/Prefabs/LeftHandUI.prefab
Assets/DongHyuk/Scripts/ButtonManager.cs

1. HandUI 버튼 OnTriggerEnter시 버튼음 발생하도록 추가.
ToDo?
1. 버튼 터치시 한 개의 버튼음이 아니라 보이는 모든 버튼에서 버튼음을 겹쳐서 뿜는 것 처럼 느껴짐. 추후 QA 후 디버그 필요

HandUI 1차 최종 - 버튼 인터랙션 SFX 추가

---

Assets/TaeHyeon/Scripts/Hands/HandController.cs
Assets/TaeHyeon/Scripts/Managers/InteractManager.cs
Assets/TaeHyeon/Scripts/Pets/IntroPetController.cs

1. 펫 선택 안하고 다른 씬으로 넘어가는 경우, savestat 호출 오류 수정
2. 펫 선택하기 전에 펫을 만졌을 경우, 널포인트 오류 수정

상호작용 오류 수정

---

Assets/TaeHyeon/Scenes/Intro.unity
Assets/TaeHyeon/Scripts/Managers/GameManager.cs
Assets/TaeSeung/Scene/HousingMode.unity

hotfix : 벽 비활성화, 하우징 디버깅  ui비활성화

---

Assets/Jaewon2/Prefabs/Default.prefab
Assets/Jaewon2/Scene/StoreScene.unity
Assets/Jaewon2/Script/DialogCon.cs
Assets/Jaewon2/Script/DialogCon.cs.meta
Assets/Jaewon2/Script/StoreManager.cs

현재 패널에 따라 dialog개별 출력
상점 dialog 출력
패널-가구
패널-먹이
패널-장난감

상점 dialog 출력

---

Assets/TaeHyeon/Scenes/Intro.unity
Assets/TaeHyeon/Scripts/Managers/GameManager.cs
Assets/TaeSeung/Prefab/HousingFunitureButton.prefab
Assets/TaeSeung/Scene/HousingMode.unity
Assets/TaeSeung/Script/MapInfo.cs
Assets/TaeSeung/Script/PlacementSystem.cs
Assets/TaeSeung/Script/UISystem/HousingUISystem.cs

1. 하우징 ui 표시 오류 수정
2. 하우징이 interaction모드에서 핀치되는 문제 수정
3. 하우징 튜토리얼 텍스트 추가

Grid Housing AR 최종 결산

---

Assets/TaeHyeon/Scripts/Managers/GameManager.cs
Assets/TaeSeung/Script/PlacementSystem.cs
Assets/TaeSeung/Shader/Making Shader/URP/Shader_graph_grid.mat

상호작용 하우징 크기 조절,  하우징 UI인덱싱 문제 오류 해결

---

Assets/Jaewon2/Prefabs/VerticalSphereSparkleExplosion.prefab
Assets/Jaewon2/Prefabs/VerticalSphereSparkleExplosion.prefab.meta
Assets/Jaewon2/Scene/StoreScene.unity
Assets/Jaewon2/Script/BuySellEffectController.cs
Assets/Jaewon2/Script/BuySellEffectController.cs.meta
Assets/Jaewon2/Script/UICon.cs
Assets/TaeHyeon/Images/grab.png.meta
Assets/TaeHyeon/Scenes/InteractMode.unity
Assets/TaeHyeon/Scripts/Tutorial/InteractTutorial.cs

상호작용 모드에서 대화창에 grab이미지 추가
상점 파트 구매, 판매버튼 이펙트 적용
상점에서 상품 선택 안하고 구매/판매 버튼 누르면 생기는 오류 해결

상점 파트 오류 해결 및 이펙트 추가

---

Assets/Jaewon2/Prefabs/Default.prefab
Assets/Jaewon2/Script/DialogCon.cs
Assets/TaeHyeon/Scripts/Managers/GameManager.cs

dialog 기능수정

---

Assets/TaeHyeon/Scenes/Intro.unity
Assets/TaeHyeon/Scripts/Managers/InteractManager.cs
Assets/TaeSeung/Script/DatabaseScript/ScriptableObject/ItemDatabase.asset

아이템DB 가격 수정 및 초기 보유 아이템 목록 수정

---

Assets/DongHyuk/Prefabs/LeftHandUI.prefab
Assets/DongHyuk/Scripts/ButtonManager.cs

래디얼 아이템의 갯수를 표시합니다.
소지수가 0개여도 아이템의 아이콘은 항상 노출됩니다.
소지수가 0개일 때 아이콘을 터치하여도 아이템은 생성되지 않습니다.

Add) HandUI-Radial item Count

---

Assets/TaeHyeon/Prefabs/Comb.prefab
Assets/TaeHyeon/Prefabs/Dialog Canvas.prefab
Assets/TaeHyeon/Prefabs/Toy/BallToy.prefab
Assets/TaeHyeon/Prefabs/Toy/BirdToy.prefab
Assets/TaeHyeon/Prefabs/Toy/BoneToy.prefab
Assets/TaeHyeon/Prefabs/Toy/CrocodileToy.prefab
Assets/TaeHyeon/Prefabs/Toy/FishToy.prefab
Assets/TaeHyeon/Prefabs/Toy/LobsterToy.prefab
Assets/TaeHyeon/Prefabs/Toy/MouseToy.prefab
Assets/TaeHyeon/Prefabs/Toy/SpikyToy.prefab
Assets/TaeHyeon/Prefabs/Toy/TutorialToys.prefab
Assets/TaeHyeon/Prefabs/Tutorial Desk.prefab
Assets/TaeHyeon/Prefabs/snack/Apple.prefab
Assets/TaeHyeon/Prefabs/snack/Banana.prefab
Assets/TaeHyeon/Prefabs/snack/HalfOrange.prefab
Assets/TaeHyeon/Prefabs/snack/Orange.prefab
Assets/TaeHyeon/Prefabs/snack/Snack.prefab
Assets/TaeHyeon/Prefabs/snack/TutorialSnacks.prefab
Assets/TaeHyeon/Scripts/Dialog/DialogController.cs
Assets/TaeHyeon/Scripts/Gifts/GiftBox.cs
Assets/TaeHyeon/Scripts/Items/Snack.cs
Assets/TaeHyeon/Scripts/Items/Toy.cs
Assets/TaeHyeon/Scripts/Managers/InteractEventManager.cs
Assets/TaeHyeon/Scripts/Pets/PetBase.cs
Assets/TaeHyeon/Scripts/Tutorial/InteractTutorial.cs
Assets/TaeHyeon/Scripts/Utils/EnumTypes.cs
ProjectSettings/ProjectSettings.asset

튜토리얼 순서를 따르지 않고, 먼저 레벨업 시도하는 경우 예외처리
먹이 튜토리얼까지 마치면 모든 튜토리얼 종료
레벨업 1>2갈때만 대화창 표시
hand UI에서 아이템 꺼내면 둥둥 떠다니는 오류 수정
레벨업과 튜토리얼 대화창 분리
ProjectSetting ENABLE_LOG 해제

상호작용 모드 튜토리얼 예외처리
